package com.enttribe.topology.ingestion.core;

/**
 * Inventory SQL queries used by the topology ingestion stages.
 * Queries are copied verbatim from the original NiFi processors
 * (ProcessorRailtelProduction3040, IsisProcessor3040, SwitchProcessorRailtel)
 * so behaviour is unchanged.
 */
public final class TopologyQueries {

    private TopologyQueries() {
    }

    // ============================================================
    // LLDP / OSPF pipeline (ProcessorRailtelProduction3040)
    // ============================================================

    public static String lldpOspfParentVertex() {
        // return "SELECT 'VERTEX' AS relation, ne.ID AS id, ne.NE_NAME AS neName, ne.SOURCE AS source, ne.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, ne.LATITUDE AS latitude, ne.LONGITUDE AS longitude, ne.NE_SOURCE AS neSource, ne.NE_STATUS AS neStatus, ne.NE_TYPE AS neType, ne.NE_CATEGORY AS neCategory, ne.VENDOR AS vendor, ne.CKT_ID AS cktId, ne.IS_DELETED AS isDeleted, ne.TECHNOLOGY AS technology, pop.NEL_ID AS popId, pop.NEL_CODE AS popCode, pop.FRIENDLY_NAME AS popName, ne.DOMAIN AS domain, ne.NE_ID AS neId, ne.PM_EMS_ID AS pmEmsId, ne.FM_EMS_ID AS fmEmsId, ne.CM_EMS_ID AS cmEmsId, ne.IPV4 AS ipv4, ne.IPV6 AS ipv6, ne.MODEL AS model, ne.MAC_ADDRESS AS macAddress, ne.FRIENDLY_NAME AS friendlyName, ne.HOST_NAME AS hostname, ne.UUID AS uuid, ne.SERIAL_NUMBER AS serialNumber, l1.GEO_NAME AS geographyL1Name, l2.GEO_NAME AS geographyL2Name, l3.GEO_NAME AS geographyL3Name, l4.GEO_NAME AS geographyL4Name, neighbourNE.NE_ID AS neighbourNEId, neighbourNE.NE_NAME AS neighbourNEName, neighbourNE.LATITUDE AS neighbourNELat, neighbourNE.LONGITUDE AS neighbourNELong, parentNE.NE_NAME AS parentNE, neighbourParentNE.NE_NAME AS neighbourParentNEName, neighbourParentNE.LONGITUDE AS neighbourParentNELong, neighbourParentNE.LATITUDE AS neighbourParentNELat FROM NETWORK_ELEMENT ne LEFT JOIN NE_LOCATION pop ON ne.NE_LOCATION_ID_FK = pop.ID LEFT JOIN PRIMARY_GEO_L1 l1 ON pop.GEOGRAPHY_L1_ID_FK = l1.id LEFT JOIN PRIMARY_GEO_L2 l2 ON pop.GEOGRAPHY_L2_ID_FK = l2.id LEFT JOIN PRIMARY_GEO_L3 l3 ON pop.GEOGRAPHY_L3_ID_FK = l3.id LEFT JOIN PRIMARY_GEO_L4 l4 ON pop.GEOGRAPHY_L4_ID_FK = l4.id LEFT JOIN NETWORK_ELEMENT parentNE ON ne.PARENT_NE_ID_FK = parentNE.ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON ne.NETWORK_ELEMENT_ID_FK = neighbourNE.ID LEFT JOIN NETWORK_ELEMENT neighbourParentNE ON neighbourNE.PARENT_NE_ID_FK = neighbourParentNE.ID WHERE ne.IS_DELETED = 0 AND DATE(ne.LAST_DISCOVERY_TIME) = CURRENT_DATE AND ne.NE_TYPE IN ('GNE','ILA','MDWDM','NIC','NODE','OADM','OTN','ROUTER') AND ne.NE_CATEGORY IN ('GATEWAY_INTERFACE','OPTICAL_AMPLIFIERS','DWDM','OTN','NODE','ROUTER')";
return "SELECT 'VERTEX' AS relation, ne.ID AS id, ne.NE_NAME AS neName, ne.SOURCE AS source, ne.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, ne.LATITUDE AS latitude, ne.LONGITUDE AS longitude, ne.NE_SOURCE AS neSource, ne.NE_STATUS AS neStatus, ne.NE_TYPE AS neType, ne.NE_CATEGORY AS neCategory, ne.VENDOR AS vendor, ne.CKT_ID AS cktId, ne.IS_DELETED AS isDeleted, ne.TECHNOLOGY AS technology, pop.NEL_ID AS popId, pop.NEL_CODE AS popCode, pop.FRIENDLY_NAME AS popName, ne.DOMAIN AS domain, ne.NE_ID AS neId, ne.PM_EMS_ID AS pmEmsId, ne.FM_EMS_ID AS fmEmsId, ne.CM_EMS_ID AS cmEmsId, ne.IPV4 AS ipv4, ne.IPV6 AS ipv6, ne.MODEL AS model, ne.MAC_ADDRESS AS macAddress, ne.FRIENDLY_NAME AS friendlyName, ne.HOST_NAME AS hostname, ne.UUID AS uuid, ne.SERIAL_NUMBER AS serialNumber, l1.GEO_NAME AS geographyL1Name, l2.GEO_NAME AS geographyL2Name, l3.GEO_NAME AS geographyL3Name, l4.GEO_NAME AS geographyL4Name, neighbourNE.NE_ID AS neighbourNEId, neighbourNE.NE_NAME AS neighbourNEName, neighbourNE.LATITUDE AS neighbourNELat, neighbourNE.LONGITUDE AS neighbourNELong, parentNE.NE_NAME AS parentNE, neighbourParentNE.NE_NAME AS neighbourParentNEName, neighbourParentNE.LONGITUDE AS neighbourParentNELong, neighbourParentNE.LATITUDE AS neighbourParentNELat FROM NETWORK_ELEMENT ne LEFT JOIN NE_LOCATION pop ON ne.NE_LOCATION_ID_FK = pop.ID LEFT JOIN PRIMARY_GEO_L1 l1 ON pop.GEOGRAPHY_L1_ID_FK = l1.id LEFT JOIN PRIMARY_GEO_L2 l2 ON pop.GEOGRAPHY_L2_ID_FK = l2.id LEFT JOIN PRIMARY_GEO_L3 l3 ON pop.GEOGRAPHY_L3_ID_FK = l3.id LEFT JOIN PRIMARY_GEO_L4 l4 ON pop.GEOGRAPHY_L4_ID_FK = l4.id LEFT JOIN NETWORK_ELEMENT parentNE ON ne.PARENT_NE_ID_FK = parentNE.ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON ne.NETWORK_ELEMENT_ID_FK = neighbourNE.ID LEFT JOIN NETWORK_ELEMENT neighbourParentNE ON neighbourNE.PARENT_NE_ID_FK = neighbourParentNE.ID WHERE ne.IS_DELETED = 0 AND ne.NE_TYPE IN ('GNE','ILA','MDWDM','NIC','NODE','OADM','OTN','ROUTER') AND ne.NE_CATEGORY IN ('GATEWAY_INTERFACE','OPTICAL_AMPLIFIERS','DWDM','OTN','NODE','ROUTER')";

    }

    public static String neighbourInterfaceForLldp() {
        return "SELECT DISTINCT 'LLDP' AS relation, src.ID AS id, src.NE_NAME AS neName, src.NE_TYPE AS neType, l.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, src.LATITUDE AS latitude, src.LONGITUDE AS longitude, src.CAPACITY AS bandwidth, src.NE_SOURCE AS neSource, src.NE_STATUS AS neStatus, src.CKT_ID AS cktId, src.IS_DELETED AS isDeleted, src.NE_ID AS neId, src.PM_EMS_ID AS pmEmsId, src.FM_EMS_ID AS fmEmsId, src.CM_EMS_ID AS cmEmsId, src.IPV4 AS ipv4, src.IPV6 AS ipv6, src.MODEL AS model, src.MAC_ADDRESS AS macAddress, src.FRIENDLY_NAME AS friendlyName, l.LLDP_LINK_NAME AS hostname, src.UUID AS uuid, src.SERIAL_NUMBER AS serialNumber, parentSrc.NE_NAME AS parentNE FROM LLDP_LINK l JOIN NETWORK_ELEMENT src ON l.SOURCE_INTERFACE_NE_ID = src.ID or l.DESTINATION_INTERFACE_NE_ID = src.ID LEFT JOIN NETWORK_ELEMENT parentSrc ON src.PARENT_NE_ID_FK = parentSrc.ID WHERE parentSrc.IS_DELETED = 0 AND (parentSrc.NE_TYPE IN ('ROUTER') OR parentSrc.NE_CATEGORY IN ('ROUTER'))";
    }

    public static String childInterfaceForLldp() {
        return "SELECT 'LLDP' AS relation, src.ID AS id, src.NE_NAME AS neName, link.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, parentSrc.LATITUDE AS latitude, parentSrc.LONGITUDE AS longitude, src.CAPACITY AS srcBandwidth, dest.CAPACITY AS destBandwidth, src.NE_SOURCE AS neSource, src.NE_STATUS AS neStatus, parentSrc.NE_TYPE AS srcType, parentDest.NE_TYPE AS destType, src.NE_TYPE AS neType, parentSrc.NE_CATEGORY AS srcCategory, parentDest.NE_CATEGORY AS destCategory, parentSrc.VENDOR AS srcVendor, parentDest.VENDOR AS destVendor, src.CKT_ID AS cktId, src.IS_DELETED AS isDeleted, parentSrc.TECHNOLOGY AS srcTechnology, parentDest.TECHNOLOGY AS destTechnology, parentSrc.DOMAIN AS srcDomain, parentDest.DOMAIN AS destDomain, src.NE_ID AS neId, src.PM_EMS_ID AS pmEmsId, src.FM_EMS_ID AS fmEmsId, src.CM_EMS_ID AS cmEmsId, src.IPV4 AS ipv4, src.IPV6 AS ipv6, src.MODEL AS model, src.MAC_ADDRESS AS macAddress, src.FRIENDLY_NAME AS friendlyName, link.LLDP_LINK_NAME AS hostname, src.UUID AS uuid, src.SERIAL_NUMBER AS serialNumber, dest.NE_ID AS neighbourNEId, dest.NE_NAME AS neighbourNEName, dest.LATITUDE AS neighbourNELat, dest.LONGITUDE AS neighbourNELong, parentSrc.NE_NAME AS parentNE, parentDest.NE_NAME AS neighbourParentNEName, parentDest.LONGITUDE AS neighbourParentNELong, parentDest.LATITUDE AS neighbourParentNELat FROM LLDP_LINK link JOIN NETWORK_ELEMENT src ON src.ID = link.SOURCE_INTERFACE_NE_ID JOIN NETWORK_ELEMENT dest ON dest.ID = link.DESTINATION_INTERFACE_NE_ID LEFT JOIN NETWORK_ELEMENT parentSrc ON src.PARENT_NE_ID_FK = parentSrc.ID LEFT JOIN NETWORK_ELEMENT parentDest ON dest.PARENT_NE_ID_FK = parentDest.ID WHERE link.IS_DELETED = 0 AND src.IS_DELETED = 0 AND dest.IS_DELETED = 0";
    }

    public static String neighbourInterfaceForOspf() {
        return "SELECT DISTINCT 'OSPF' AS relation, src.ID AS id, src.NE_NAME AS neName, src.NE_TYPE AS neType, l.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, src.LATITUDE AS latitude, src.LONGITUDE AS longitude, src.CAPACITY AS bandwidth, src.NE_SOURCE AS neSource, src.NE_STATUS AS neStatus, src.CKT_ID AS cktId, src.IS_DELETED AS isDeleted, src.NE_ID AS neId, src.PM_EMS_ID AS pmEmsId, src.FM_EMS_ID AS fmEmsId, src.CM_EMS_ID AS cmEmsId, src.IPV4 AS ipv4, src.IPV6 AS ipv6, src.MODEL AS model, src.MAC_ADDRESS AS macAddress, src.FRIENDLY_NAME AS friendlyName, src.UUID AS uuid, src.SERIAL_NUMBER AS serialNumber, parentSrc.NE_NAME AS parentNE FROM OSPF_LINK l JOIN NETWORK_ELEMENT src ON l.SOURCE_INTERFACE_NE_ID = src.ID or l.DESTINATION_INTERFACE_NE_ID = src.ID LEFT JOIN NETWORK_ELEMENT parentSrc ON src.PARENT_NE_ID_FK = parentSrc.ID WHERE parentSrc.IS_DELETED = 0 AND (parentSrc.NE_TYPE IN ('ROUTER') OR parentSrc.NE_CATEGORY IN ('ROUTER'))";
    }

    public static String childInterfaceForOspf() {
        // return "SELECT DISTINCT 'OSPF' AS relation, ospf.CKT_ID AS cktId, ne.ID AS id, ne.NE_NAME AS neName, COALESCE(src.LATITUDE, ne.LATITUDE) AS latitude, COALESCE(src.LONGITUDE, ne.LONGITUDE) AS longitude, ne.NE_TYPE AS neType, ospf.TAG AS tag, ospf.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, ne.CAPACITY AS srcBandwidth, neighbourNE.CAPACITY AS destBandwidth, ospf.AREA_IP_ADDRESS AS areaIpAddress, ne.NE_SOURCE AS neSource, ne.NE_STATUS AS neStatus, COALESCE(src.NE_TYPE, ne.NE_TYPE) AS srcType, COALESCE(rem.NE_TYPE, neighbourNE.NE_TYPE) AS destType, COALESCE(src.NE_CATEGORY, ne.NE_CATEGORY) AS srcCategory, COALESCE(rem.NE_CATEGORY, neighbourNE.NE_CATEGORY) AS destCategory, COALESCE(src.VENDOR, ne.VENDOR) AS srcVendor, COALESCE(rem.VENDOR, neighbourNE.VENDOR) AS destVendor, ne.IS_DELETED AS isDeleted, COALESCE(src.TECHNOLOGY, ne.TECHNOLOGY) AS srcTechnology, COALESCE(rem.TECHNOLOGY, neighbourNE.TECHNOLOGY) AS destTechnology, COALESCE(src.DOMAIN, ne.DOMAIN) AS srcDomain, COALESCE(rem.DOMAIN, neighbourNE.DOMAIN) AS destDomain, ne.NE_ID AS neId, ne.PM_EMS_ID AS pmEmsId, ne.FM_EMS_ID AS fmEmsId, ne.CM_EMS_ID AS cmEmsId, ne.IPV4 AS ipv4, ne.IPV6 AS ipv6, ne.MODEL AS model, ne.MAC_ADDRESS AS macAddress, ne.FRIENDLY_NAME AS friendlyName, ne.HOST_NAME AS hostname, ne.UUID AS uuid, ne.SERIAL_NUMBER AS serialNumber, neighbourNE.NE_ID AS neighbourNEId, neighbourNE.NE_NAME AS neighbourNEName, COALESCE(neighbourNE.LATITUDE, rem.LATITUDE) AS neighbourNELat, COALESCE(neighbourNE.LONGITUDE, rem.LONGITUDE) AS neighbourNELong, COALESCE(src.NE_NAME, ne.NE_NAME) AS parentNE, COALESCE(rem.NE_NAME, neighbourNE.NE_NAME) AS neighbourParentNEName, COALESCE(rem.LONGITUDE, neighbourNE.longitude) AS neighbourParentNELong, COALESCE(rem.LATITUDE, neighbourNE.LATITUDE) AS neighbourParentNELat FROM OSPF_LINK ospf INNER JOIN NETWORK_ELEMENT src ON src.ID = ospf.SOURCE_NE_ID INNER JOIN NETWORK_ELEMENT rem ON rem.ID = ospf.DESTINATION_NE_ID LEFT JOIN NETWORK_ELEMENT ne ON ne.ID = ospf.SOURCE_INTERFACE_NE_ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON neighbourNE.ID = ospf.DESTINATION_INTERFACE_NE_ID WHERE ne.IS_DELETED = 0 AND DATE(ospf.LAST_DISCOVERY_TIME) = CURRENT_DATE AND neighbourNE.IS_DELETED = 0 AND ne.NE_TYPE = 'INTERFACE' AND neighbourNE.NE_TYPE = 'INTERFACE' ORDER BY src.ID ASC";
        return "SELECT DISTINCT 'OSPF' AS relation, ospf.CKT_ID AS cktId, ne.ID AS id, ne.NE_NAME AS neName, COALESCE(src.LATITUDE, ne.LATITUDE) AS latitude, COALESCE(src.LONGITUDE, ne.LONGITUDE) AS longitude, ne.NE_TYPE AS neType, ospf.TAG AS tag, ospf.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, ne.CAPACITY AS srcBandwidth, neighbourNE.CAPACITY AS destBandwidth, ospf.AREA_IP_ADDRESS AS areaIpAddress, ne.NE_SOURCE AS neSource, ne.NE_STATUS AS neStatus, COALESCE(src.NE_TYPE, ne.NE_TYPE) AS srcType, COALESCE(rem.NE_TYPE, neighbourNE.NE_TYPE) AS destType, COALESCE(src.NE_CATEGORY, ne.NE_CATEGORY) AS srcCategory, COALESCE(rem.NE_CATEGORY, neighbourNE.NE_CATEGORY) AS destCategory, COALESCE(src.VENDOR, ne.VENDOR) AS srcVendor, COALESCE(rem.VENDOR, neighbourNE.VENDOR) AS destVendor, ne.IS_DELETED AS isDeleted, COALESCE(src.TECHNOLOGY, ne.TECHNOLOGY) AS srcTechnology, COALESCE(rem.TECHNOLOGY, neighbourNE.TECHNOLOGY) AS destTechnology, COALESCE(src.DOMAIN, ne.DOMAIN) AS srcDomain, COALESCE(rem.DOMAIN, neighbourNE.DOMAIN) AS destDomain, ne.NE_ID AS neId, ne.PM_EMS_ID AS pmEmsId, ne.FM_EMS_ID AS fmEmsId, ne.CM_EMS_ID AS cmEmsId, ne.IPV4 AS ipv4, ne.IPV6 AS ipv6, ne.MODEL AS model, ne.MAC_ADDRESS AS macAddress, ne.FRIENDLY_NAME AS friendlyName, ne.HOST_NAME AS hostname, ne.UUID AS uuid, ne.SERIAL_NUMBER AS serialNumber, neighbourNE.NE_ID AS neighbourNEId, neighbourNE.NE_NAME AS neighbourNEName, COALESCE(neighbourNE.LATITUDE, rem.LATITUDE) AS neighbourNELat, COALESCE(neighbourNE.LONGITUDE, rem.LONGITUDE) AS neighbourNELong, COALESCE(src.NE_NAME, ne.NE_NAME) AS parentNE, COALESCE(rem.NE_NAME, neighbourNE.NE_NAME) AS neighbourParentNEName, COALESCE(rem.LONGITUDE, neighbourNE.longitude) AS neighbourParentNELong, COALESCE(rem.LATITUDE, neighbourNE.LATITUDE) AS neighbourParentNELat FROM OSPF_LINK ospf INNER JOIN NETWORK_ELEMENT src ON src.ID = ospf.SOURCE_NE_ID INNER JOIN NETWORK_ELEMENT rem ON rem.ID = ospf.DESTINATION_NE_ID LEFT JOIN NETWORK_ELEMENT ne ON ne.ID = ospf.SOURCE_INTERFACE_NE_ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON neighbourNE.ID = ospf.DESTINATION_INTERFACE_NE_ID WHERE ne.IS_DELETED = 0 AND neighbourNE.IS_DELETED = 0 AND ne.NE_TYPE = 'INTERFACE' AND neighbourNE.NE_TYPE = 'INTERFACE' ORDER BY src.ID ASC";

    }

    // ============================================================
    // ISIS pipeline (IsisProcessor3040) — SDN-sourced parent vertex
    // ============================================================

    public static String isisParentVertex() {
        return "SELECT 'VERTEX' AS relation, ne.ID AS id, ne.NE_NAME AS neName, ne.SOURCE AS source , ne.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, ne.LATITUDE AS latitude, ne.LONGITUDE AS longitude, ne.NE_SOURCE AS neSource, ne.NE_STATUS AS neStatus, ne.NE_TYPE AS neType, ne.NE_CATEGORY AS neCategory, ne.VENDOR AS vendor, ne.CKT_ID AS cktId, ne.IS_DELETED AS isDeleted, ne.TECHNOLOGY AS technology, pop.NEL_ID AS popId, pop.NEL_CODE AS popCode, pop.FRIENDLY_NAME AS popName, ne.DOMAIN AS domain, ne.NE_ID AS neId, ne.PM_EMS_ID AS pmEmsId, ne.FM_EMS_ID AS fmEmsId, ne.CM_EMS_ID AS cmEmsId, ne.IPV4 AS ipv4, ne.IPV6 AS ipv6, ne.MODEL AS model, ne.MAC_ADDRESS AS macAddress, ne.FRIENDLY_NAME AS friendlyName, ne.HOST_NAME AS hostname, ne.UUID AS uuid, ne.SERIAL_NUMBER AS serialNumber, l1.GEO_NAME AS geographyL1Name, l2.GEO_NAME AS geographyL2Name, l3.GEO_NAME AS geographyL3Name, l4.GEO_NAME AS geographyL4Name, neighbourNE.NE_ID AS neighbourNEId, neighbourNE.NE_NAME AS neighbourNEName, neighbourNE.LATITUDE AS neighbourNELat, neighbourNE.LONGITUDE AS neighbourNELong, parentNE.NE_NAME AS parentNE, neighbourParentNE.NE_NAME AS neighbourParentNEName, neighbourParentNE.LONGITUDE AS neighbourParentNELong, neighbourParentNE.LATITUDE AS neighbourParentNELat FROM NETWORK_ELEMENT ne LEFT JOIN NE_LOCATION pop ON ne.NE_LOCATION_ID_FK = pop.ID LEFT JOIN PRIMARY_GEO_L1 l1 ON pop.GEOGRAPHY_L1_ID_FK = l1.id LEFT JOIN PRIMARY_GEO_L2 l2 ON pop.GEOGRAPHY_L2_ID_FK = l2.id LEFT JOIN PRIMARY_GEO_L3 l3 ON pop.GEOGRAPHY_L3_ID_FK = l3.id LEFT JOIN PRIMARY_GEO_L4 l4 ON pop.GEOGRAPHY_L4_ID_FK = l4.id LEFT JOIN NETWORK_ELEMENT parentNE ON ne.PARENT_NE_ID_FK = parentNE.ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON ne.NETWORK_ELEMENT_ID_FK = neighbourNE.ID LEFT JOIN NETWORK_ELEMENT neighbourParentNE ON neighbourNE.PARENT_NE_ID_FK = neighbourParentNE.ID WHERE ne.IS_DELETED = 0 AND ne.SOURCE= 'SDN' AND  ne.NE_TYPE IN ('GNE','ILA','MDWDM','NIC','NODE','OADM','OTN','ROUTER') AND ne.NE_CATEGORY IN ('GATEWAY_INTERFACE','OPTICAL_AMPLIFIERS','DWDM','OTN','NODE','ROUTER')";
    }

    public static String neighbourInterfaceForIsis() {
        // return "SELECT DISTINCT 'ISIS' AS relation, neighbourNE.ID AS id, neighbourNE.NE_NAME AS neName, neighbourNE.NE_TYPE AS neType, ospf.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, neighbourNE.NE_SOURCE AS neSource, neighbourNE.BANDWIDTH AS bandwidth, neighbourNE.NE_STATUS AS neStatus, ospf.UUID AS uuid, neighbourNE.IS_DELETED AS isDeleted, neighbourNE.NE_ID AS neId, neighbourNE.PM_EMS_ID AS pmEmsId, neighbourNE.FM_EMS_ID AS fmEmsId, neighbourNE.CM_EMS_ID AS cmEmsId, neighbourNE.IPV4 AS ipv4, neighbourNE.IPV6 AS ipv6, neighbourNE.MODEL AS model, neighbourNE.MAC_ADDRESS AS macAddress, neighbourNE.FRIENDLY_NAME AS friendlyName, neighbourNE.HOST_NAME AS hostname, neighbourNE.UUID AS uuid, neighbourNE.SERIAL_NUMBER AS serialNumber FROM ISIS_LINK ospf INNER JOIN NETWORK_ELEMENT src ON src.ID = ospf.SOURCE_NE_ID INNER JOIN NETWORK_ELEMENT rem ON rem.ID = ospf.DESTINATION_NE_ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON neighbourNE.ID = ospf.SOURCE_INTERFACE_NE_ID OR neighbourNE.ID = ospf.DESTINATION_INTERFACE_NE_ID WHERE neighbourNE.IS_DELETED = 0 AND DATE(ospf.LAST_DISCOVERY_TIME) = CURRENT_DATE AND neighbourNE.NE_TYPE = 'INTERFACE' ORDER BY rem.ID ASC";
        return "SELECT DISTINCT 'ISIS' AS relation, neighbourNE.ID AS id, neighbourNE.NE_NAME AS neName, neighbourNE.NE_TYPE AS neType, ospf.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, neighbourNE.NE_SOURCE AS neSource, neighbourNE.BANDWIDTH AS bandwidth, neighbourNE.NE_STATUS AS neStatus, ospf.UUID AS uuid, neighbourNE.IS_DELETED AS isDeleted, neighbourNE.NE_ID AS neId, neighbourNE.PM_EMS_ID AS pmEmsId, neighbourNE.FM_EMS_ID AS fmEmsId, neighbourNE.CM_EMS_ID AS cmEmsId, neighbourNE.IPV4 AS ipv4, neighbourNE.IPV6 AS ipv6, neighbourNE.MODEL AS model, neighbourNE.MAC_ADDRESS AS macAddress, neighbourNE.FRIENDLY_NAME AS friendlyName, neighbourNE.HOST_NAME AS hostname, neighbourNE.UUID AS uuid, neighbourNE.SERIAL_NUMBER AS serialNumber FROM ISIS_LINK ospf INNER JOIN NETWORK_ELEMENT src ON src.ID = ospf.SOURCE_NE_ID INNER JOIN NETWORK_ELEMENT rem ON rem.ID = ospf.DESTINATION_NE_ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON neighbourNE.ID = ospf.SOURCE_INTERFACE_NE_ID OR neighbourNE.ID = ospf.DESTINATION_INTERFACE_NE_ID WHERE neighbourNE.IS_DELETED = 0  AND neighbourNE.NE_TYPE = 'INTERFACE' ORDER BY rem.ID ASC";

    }

    public static String childInterfaceForIsis() {
        // return "SELECT DISTINCT 'ISIS' AS relation, ne.ID AS id, ospf.CKT_ID AS cktId, ne.NE_NAME AS neName, COALESCE(src.LATITUDE, ne.LATITUDE) AS latitude, COALESCE(src.LONGITUDE, ne.LONGITUDE) AS longitude, ne.NE_TYPE AS neType, ospf.LINK_TYPE AS linkType, ospf.TAG AS tag, ospf.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, ne.BANDWIDTH AS srcBandwidth,  neighbourNE.BANDWIDTH AS destBandwidth, ne.NE_SOURCE AS neSource, ne.NE_STATUS AS neStatus, ospf.UUID AS uuid, COALESCE(src.NE_TYPE, ne.NE_TYPE) AS srcType, COALESCE(rem.NE_TYPE, neighbourNE.NE_TYPE) AS destType, COALESCE(src.NE_CATEGORY, ne.NE_CATEGORY) AS srcCategory, COALESCE(rem.NE_CATEGORY, neighbourNE.NE_CATEGORY) AS destCategory, COALESCE(src.VENDOR, ne.VENDOR) AS srcVendor, COALESCE(rem.VENDOR, neighbourNE.VENDOR) AS destVendor, ne.IS_DELETED AS isDeleted, COALESCE(src.TECHNOLOGY, ne.TECHNOLOGY) AS srcTechnology, COALESCE(rem.TECHNOLOGY, neighbourNE.TECHNOLOGY) AS destTechnology, COALESCE(src.DOMAIN, ne.DOMAIN) AS srcDomain, COALESCE(rem.DOMAIN, neighbourNE.DOMAIN) AS destDomain, ne.NE_ID AS neId, ne.PM_EMS_ID AS pmEmsId, ne.FM_EMS_ID AS fmEmsId, ne.CM_EMS_ID AS cmEmsId, ne.IPV4 AS ipv4, ne.IPV6 AS ipv6, ne.MODEL AS model, ne.MAC_ADDRESS AS macAddress, ne.FRIENDLY_NAME AS friendlyName, ne.HOST_NAME AS hostname, ne.UUID AS uuid, ne.SERIAL_NUMBER AS serialNumber, neighbourNE.NE_ID AS neighbourNEId, neighbourNE.NE_NAME AS neighbourNEName, COALESCE(neighbourNE.LATITUDE, rem.LATITUDE) AS neighbourNELat, COALESCE(neighbourNE.LONGITUDE, rem.LONGITUDE) AS neighbourNELong, COALESCE(src.NE_NAME, ne.NE_NAME) AS parentNE, COALESCE(rem.NE_NAME, neighbourNE.NE_NAME) AS neighbourParentNEName, COALESCE(rem.LONGITUDE, neighbourNE.longitude) AS neighbourParentNELong, COALESCE(rem.LATITUDE, neighbourNE.LATITUDE) AS neighbourParentNELat FROM ISIS_LINK ospf INNER JOIN NETWORK_ELEMENT src ON src.ID = ospf.SOURCE_NE_ID  INNER JOIN NETWORK_ELEMENT rem ON rem.ID = ospf.DESTINATION_NE_ID LEFT JOIN NETWORK_ELEMENT ne ON ne.ID = ospf.SOURCE_INTERFACE_NE_ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON neighbourNE.ID = ospf.DESTINATION_INTERFACE_NE_ID  WHERE ne.IS_DELETED = 0 AND neighbourNE.IS_DELETED = 0 AND ne.NE_TYPE = 'INTERFACE' AND DATE(ospf.LAST_DISCOVERY_TIME) = CURRENT_DATE AND neighbourNE.NE_TYPE = 'INTERFACE' ORDER BY src.ID ASC";
                return "SELECT DISTINCT 'ISIS' AS relation, ne.ID AS id, ospf.CKT_ID AS cktId, ne.NE_NAME AS neName, COALESCE(src.LATITUDE, ne.LATITUDE) AS latitude, COALESCE(src.LONGITUDE, ne.LONGITUDE) AS longitude, ne.NE_TYPE AS neType, ospf.LINK_TYPE AS linkType, ospf.TAG AS tag, ospf.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, ne.BANDWIDTH AS srcBandwidth,  neighbourNE.BANDWIDTH AS destBandwidth, ne.NE_SOURCE AS neSource, ne.NE_STATUS AS neStatus, ospf.UUID AS uuid, COALESCE(src.NE_TYPE, ne.NE_TYPE) AS srcType, COALESCE(rem.NE_TYPE, neighbourNE.NE_TYPE) AS destType, COALESCE(src.NE_CATEGORY, ne.NE_CATEGORY) AS srcCategory, COALESCE(rem.NE_CATEGORY, neighbourNE.NE_CATEGORY) AS destCategory, COALESCE(src.VENDOR, ne.VENDOR) AS srcVendor, COALESCE(rem.VENDOR, neighbourNE.VENDOR) AS destVendor, ne.IS_DELETED AS isDeleted, COALESCE(src.TECHNOLOGY, ne.TECHNOLOGY) AS srcTechnology, COALESCE(rem.TECHNOLOGY, neighbourNE.TECHNOLOGY) AS destTechnology, COALESCE(src.DOMAIN, ne.DOMAIN) AS srcDomain, COALESCE(rem.DOMAIN, neighbourNE.DOMAIN) AS destDomain, ne.NE_ID AS neId, ne.PM_EMS_ID AS pmEmsId, ne.FM_EMS_ID AS fmEmsId, ne.CM_EMS_ID AS cmEmsId, ne.IPV4 AS ipv4, ne.IPV6 AS ipv6, ne.MODEL AS model, ne.MAC_ADDRESS AS macAddress, ne.FRIENDLY_NAME AS friendlyName, ne.HOST_NAME AS hostname, ne.UUID AS uuid, ne.SERIAL_NUMBER AS serialNumber, neighbourNE.NE_ID AS neighbourNEId, neighbourNE.NE_NAME AS neighbourNEName, COALESCE(neighbourNE.LATITUDE, rem.LATITUDE) AS neighbourNELat, COALESCE(neighbourNE.LONGITUDE, rem.LONGITUDE) AS neighbourNELong, COALESCE(src.NE_NAME, ne.NE_NAME) AS parentNE, COALESCE(rem.NE_NAME, neighbourNE.NE_NAME) AS neighbourParentNEName, COALESCE(rem.LONGITUDE, neighbourNE.longitude) AS neighbourParentNELong, COALESCE(rem.LATITUDE, neighbourNE.LATITUDE) AS neighbourParentNELat FROM ISIS_LINK ospf INNER JOIN NETWORK_ELEMENT src ON src.ID = ospf.SOURCE_NE_ID  INNER JOIN NETWORK_ELEMENT rem ON rem.ID = ospf.DESTINATION_NE_ID LEFT JOIN NETWORK_ELEMENT ne ON ne.ID = ospf.SOURCE_INTERFACE_NE_ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON neighbourNE.ID = ospf.DESTINATION_INTERFACE_NE_ID  WHERE ne.IS_DELETED = 0 AND neighbourNE.IS_DELETED = 0 AND ne.NE_TYPE = 'INTERFACE' AND neighbourNE.NE_TYPE = 'INTERFACE' ORDER BY src.ID ASC";
    }

    // ============================================================
    // SWITCH pipeline (SwitchProcessorRailtel)
    // ============================================================

    public static String switchParentVertex() {
        return "SELECT 'VERTEX' AS relation, ne.ID AS id, ne.NE_NAME AS neName, ne.SOURCE AS source , ne.MODIFIED_TIME AS neModifyTime, ne.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, ne.LATITUDE AS latitude, ne.LONGITUDE AS longitude, ne.NE_SOURCE AS neSource, ne.NE_STATUS AS neStatus, ne.NE_TYPE AS neType, ne.NE_CATEGORY AS neCategory, ne.VENDOR AS vendor, ne.CKT_ID AS cktId, ne.IS_DELETED AS isDeleted, ne.TECHNOLOGY AS technology, pop.NEL_ID AS popId, pop.NEL_CODE AS popName, ne.DOMAIN AS domain, ne.NE_ID AS neId, ne.PM_EMS_ID AS pmEmsId, ne.FM_EMS_ID AS fmEmsId, ne.CM_EMS_ID AS cmEmsId, ne.IPV4 AS ipv4, ne.IPV6 AS ipv6, ne.MODEL AS model, ne.MAC_ADDRESS AS macAddress, ne.FRIENDLY_NAME AS friendlyName, ne.HOST_NAME AS hostname, ne.UUID AS uuid, ne.SERIAL_NUMBER AS serialNumber, l1.GEO_NAME AS geographyL1Name, l2.GEO_NAME AS geographyL2Name, l3.GEO_NAME AS geographyL3Name, l4.GEO_NAME AS geographyL4Name, neighbourNE.NE_ID AS neighbourNEId, neighbourNE.NE_NAME AS neighbourNEName, neighbourNE.LATITUDE AS neighbourNELat, neighbourNE.LONGITUDE AS neighbourNELong, parentNE.NE_NAME AS parentNE, neighbourParentNE.NE_NAME AS neighbourParentNEName, neighbourParentNE.LONGITUDE AS neighbourParentNELong, neighbourParentNE.LATITUDE AS neighbourParentNELat FROM NETWORK_ELEMENT ne LEFT JOIN NE_LOCATION pop ON ne.NE_LOCATION_ID_FK = pop.ID LEFT JOIN PRIMARY_GEO_L1 l1 ON pop.GEOGRAPHY_L1_ID_FK = l1.id LEFT JOIN PRIMARY_GEO_L2 l2 ON pop.GEOGRAPHY_L2_ID_FK = l2.id LEFT JOIN PRIMARY_GEO_L3 l3 ON pop.GEOGRAPHY_L3_ID_FK = l3.id LEFT JOIN PRIMARY_GEO_L4 l4 ON pop.GEOGRAPHY_L4_ID_FK = l4.id LEFT JOIN NETWORK_ELEMENT parentNE ON ne.PARENT_NE_ID_FK = parentNE.ID LEFT JOIN NETWORK_ELEMENT neighbourNE ON ne.NETWORK_ELEMENT_ID_FK = neighbourNE.ID LEFT JOIN NETWORK_ELEMENT neighbourParentNE ON neighbourNE.PARENT_NE_ID_FK = neighbourParentNE.ID WHERE ne.IS_DELETED = 0 AND ne.NE_TYPE IN ('SWITCH') AND ne.NE_CATEGORY IN ('SWITCH')";
    }

    public static String neighbourInterfaceForSwitch() {
        return "SELECT DISTINCT 'LLDPSWITCH' AS relation, src.ID AS id, src.NE_NAME AS neName, src.NE_TYPE AS neType, l.MODIFIED_TIME AS lldpModifyTime, src.MODIFIED_TIME AS lldpInterfaceModifyTime, l.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, src.LATITUDE AS latitude, src.LONGITUDE AS longitude, src.CAPACITY AS bandwidth, src.NE_SOURCE AS neSource, src.NE_STATUS AS neStatus, src.CKT_ID AS cktId, src.IS_DELETED AS isDeleted, src.NE_ID AS neId, src.PM_EMS_ID AS pmEmsId, src.FM_EMS_ID AS fmEmsId, src.CM_EMS_ID AS cmEmsId, src.IPV4 AS ipv4, src.IPV6 AS ipv6, src.MODEL AS model, src.MAC_ADDRESS AS macAddress, src.FRIENDLY_NAME AS friendlyName, l.LLDP_LINK_NAME AS hostname, src.UUID AS uuid, src.SERIAL_NUMBER AS serialNumber, parentSrc.NE_NAME AS parentNE FROM LLDP_LINK l JOIN NETWORK_ELEMENT src ON l.SOURCE_INTERFACE_NE_ID = src.ID or l.DESTINATION_INTERFACE_NE_ID = src.ID LEFT JOIN NETWORK_ELEMENT parentSrc ON src.PARENT_NE_ID_FK = parentSrc.ID WHERE parentSrc.IS_DELETED = 0 AND (parentSrc.NE_TYPE IN ('SWITCH') OR parentSrc.NE_CATEGORY IN ('SWITCH'))";
    }

    public static String childInterfaceForSwitch() {
        return "SELECT 'LLDPSWITCH' AS relation, src.ID AS id, src.NE_NAME AS neName, link.MODIFIED_TIME AS lldpModifyTime, src.MODIFIED_TIME AS lldpInterfaceModifyTime, link.LAST_DISCOVERY_TIME AS lastDiscoveryDateTime, parentSrc.LATITUDE AS latitude, parentSrc.LONGITUDE AS longitude, src.CAPACITY AS srcBandwidth, dest.CAPACITY AS destBandwidth, src.NE_SOURCE AS neSource, src.NE_STATUS AS neStatus, parentSrc.NE_TYPE AS srcType, parentDest.NE_TYPE AS destType, src.NE_TYPE AS neType, parentSrc.NE_CATEGORY AS srcCategory, parentDest.NE_CATEGORY AS destCategory, parentSrc.VENDOR AS srcVendor, parentDest.VENDOR AS destVendor, src.CKT_ID AS cktId, src.IS_DELETED AS isDeleted, parentSrc.TECHNOLOGY AS srcTechnology, parentDest.TECHNOLOGY AS destTechnology, parentSrc.DOMAIN AS srcDomain, parentDest.DOMAIN AS destDomain, src.NE_ID AS neId, src.PM_EMS_ID AS pmEmsId, src.FM_EMS_ID AS fmEmsId, src.CM_EMS_ID AS cmEmsId, src.IPV4 AS ipv4, src.IPV6 AS ipv6, src.MODEL AS model, src.MAC_ADDRESS AS macAddress, src.FRIENDLY_NAME AS friendlyName, link.LLDP_LINK_NAME AS hostname, src.UUID AS uuid, src.SERIAL_NUMBER AS serialNumber, dest.NE_ID AS neighbourNEId, dest.NE_NAME AS neighbourNEName, dest.LATITUDE AS neighbourNELat, dest.LONGITUDE AS neighbourNELong, parentSrc.NE_NAME AS parentNE, parentDest.NE_NAME AS neighbourParentNEName, parentDest.LONGITUDE AS neighbourParentNELong, parentDest.LATITUDE AS neighbourParentNELat FROM LLDP_LINK link JOIN NETWORK_ELEMENT src ON src.ID = link.SOURCE_INTERFACE_NE_ID JOIN NETWORK_ELEMENT dest ON dest.ID = link.DESTINATION_INTERFACE_NE_ID LEFT JOIN NETWORK_ELEMENT parentSrc ON src.PARENT_NE_ID_FK = parentSrc.ID LEFT JOIN NETWORK_ELEMENT parentDest ON dest.PARENT_NE_ID_FK = parentDest.ID WHERE link.IS_DELETED = 0 AND src.IS_DELETED = 0 AND dest.IS_DELETED = 0  AND ((parentSrc.NE_TYPE = 'SWITCH' AND parentDest.NE_TYPE IN ('SWITCH','ROUTER')) OR (parentDest.NE_TYPE = 'SWITCH' AND parentSrc.NE_TYPE IN ('SWITCH','ROUTER')))";
    }
}
